# This file was generated by GoReleaser. DO NOT EDIT.
cask "yolobox" do
  name "yolobox"
  desc "Run AI coding agents in a sandboxed container"
  homepage "https://github.com/finbarr/yolobox"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yolobox"

  on_macos do
    on_intel do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-darwin-amd64.tar.gz"
      sha256 "0d5a3cfd41c87e5f9fda07296b312f8dc0f75646bf8d81e811efb06514053cf1"
    end
    on_arm do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-darwin-arm64.tar.gz"
      sha256 "489983f4e07cff4aec9be8c5079aea56161e81c07b1bc4cdd5b765f13fd708be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-linux-amd64.tar.gz"
      sha256 "22f3ac18564f7fad332dee797d38df4d46497be1b80d2f6c254e0c8c97948b2f"
    end
    on_arm do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-linux-arm64.tar.gz"
      sha256 "ff312ce119fc82a3e1271fe25b2bba6103af8ba558662e6b86fe472e66e8326f"
    end
  end

  caveats do
    "yolobox requires Docker or Podman to run containers."
    "Make sure you have one installed and running."
  end

  # No zap stanza required
end
