# This file was generated by GoReleaser. DO NOT EDIT.
cask "yolobox" do
  name "yolobox"
  desc "Run AI coding agents in a sandboxed container"
  homepage "https://github.com/finbarr/yolobox"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yolobox"

  on_macos do
    on_intel do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-darwin-amd64.tar.gz"
      sha256 "8248f3495bb5230922a1547433e22e2ece92a994db2b00be79c11090f0ccea43"
    end
    on_arm do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-darwin-arm64.tar.gz"
      sha256 "0e0874adabd5731258cad1856518e780aeb819b9b4a356a9b5d311807d644a57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-linux-amd64.tar.gz"
      sha256 "e755e901f4a4e4651d1ff952750f2a09bf5858ca1c37d7d8847c64434eebb897"
    end
    on_arm do
      url "https://github.com/finbarr/yolobox/releases/download/v#{version}/yolobox-linux-arm64.tar.gz"
      sha256 "6ad8eb9194be66e9051c43152e62a6f74990f01b51795c5f112c80d3528c0350"
    end
  end

  caveats do
    "yolobox requires Docker or Podman to run containers."
    "Make sure you have one installed and running."
  end

  # No zap stanza required
end
